name: vits-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - torch==2.10.0 --index-url https://download.pytorch.org/whl/cpu
    - torchaudio==2.10.0 --index-url https://download.pytorch.org/whl/cpu
    - torchvision==0.15.0 --index-url https://download.pytorch.org/whl/cpu
    - librosa==0.11.0
    - soundfile==0.13.1
    - numpy==2.3.5
    - scipy==1.17.0
    - matplotlib==3.10.8
    - tensorboard==2.15.1
    - pyyaml==6.0.1
    - tqdm==4.66.1
    - jupyter==1.0.0
